stages:
  - sync

sync_to_github:
  stage: sync
  image: alpine:latest
  only:
    - main
  script:
    - apk add --no-cache git openssh
    - git config --global user.email "lemanhddt@gmail.com"
    - git config --global user.name "leem28"
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/LeeManh/wallet.git
    - git push --force github HEAD:main
