
#include "services/AuthService.hpp"

#include <tuple>

#include "exceptions/Exception.hpp"
#include "models/User.hpp"
#include "services/OtpService.hpp"
#include "services/UserService.hpp"
#include "services/WalletService.hpp"
#include "utils/ExceptionHandler.hpp"
#include "utils/Hash.hpp"
#include "utils/Input.hpp"
#include "utils/MessageHandler.hpp"
#include "utils/Password.hpp"
#include "utils/Storage.hpp"

namespace services {

std::tuple<bool, int, bool, bool> AuthService::login(
    const std::string& username, const std::string& password) {
  json users = utils::storage::readJsonFile("data/users.json");

  for (const auto& user : users) {
    if (user["username"] == username) {
      bool isMatchPassword =
          utils::hash::validatePassword(password, user["passwordHash"]);
      bool isPasswordAutoGenerated =
          user["isPasswordAutoGenerated"].get<bool>();
      if (!isMatchPassword)
        throw exceptions::AuthException(
            "Tên đăng nhập hoặc mật khẩu không đúng!");

      return {true, user["id"], user["isAdmin"], isPasswordAutoGenerated};
    }
  }

  throw exceptions::AuthException("Tài khoản không tồn tại");
}

bool AuthService::registerUser(const std::string& username,
                               const std::string& password,
                               const std::string& email,
                               const std::string& fullName) {
  // Validate data
  UserService::validateUserData(username, email);

  // Tạo user mới
  models::User newUser =
      UserService::createUser(username, password, email, fullName);

  // Tự động tạo ví cho user mới
  try {
    WalletService::createWallet(newUser.getId(), 0.0);
  } catch (const std::exception& e) {
    // Rollback user creation
    UserService::deleteUser(newUser.getId());

    throw;
  }

  return true;
}

bool AuthService::registerUserByAdmin(const std::string& username,
                                      const std::string& email,
                                      const std::string& fullName,
                                      std::string& generatedPassword) {
  // Validate data
  UserService::validateUserData(username, email);

  // Tạo user mới
  generatedPassword = utils::password::generateRandomPassword(8);
  models::User newUser = UserService::createUser(username, generatedPassword,
                                                 email, fullName, false, true);

  // Tự động tạo ví cho user mới
  try {
    WalletService::createWallet(newUser.getId(), 0.0);
  } catch (const std::exception& e) {
    // Rollback user creation
    UserService::deleteUser(newUser.getId());

    throw;
  }

  return true;
}

void AuthService::otpValidation(const int userId, const std::string& email) {
  // Input OTP
  utils::MessageHandler::logMessage("Gửi mã OTP để xác thực...");
  services::OtpService::generateAndSendOTP(userId, email,
                                           enums::OTPType::INFO_CHANGE);

  // Tạo và xác minh OTP
  std::string otpCode = utils::input::getInput("Nhập mã OTP đã được gửi: ");
  utils::MessageHandler::logMessage(
      "───────────────────────────────────────────────");

  services::OtpService::verifyOTP(userId, otpCode, enums::OTPType::INFO_CHANGE);
}

bool AuthService::editUserInfo(int userId, const std::string& newFullName,
                               const std::string& newEmail) {
  // Validate new email
  UserService::validateUserEmail(userId, newEmail);

  json users = utils::storage::readJsonFile("data/users.json");
  bool found = false;

  for (auto& user : users) {
    if (user["id"] == userId) {
      if (!newFullName.empty()) {
        user["fullName"] = newFullName;
      }
      if (!newEmail.empty()) {
        otpValidation(userId, newEmail);
        user["email"] = newEmail;
      }
      found = true;
      break;
    }
  }

  if (!found) {
    throw exceptions::NotFoundException("User không tồn tại");
  }

  utils::storage::writeJsonFile("data/users.json", users);
  return true;
}

bool AuthService::changePassword(int userId, const std::string& currentPassword,
                                 const std::string& newPassword) {
  auto userJson = UserService::findUserById(userId);

  if (!userJson.has_value())
    throw exceptions::NotFoundException("User không tồn tại");

  // Kiểm tra mật khẩu có đúng không
  bool isMatchPassword = utils::hash::validatePassword(
      currentPassword, userJson.value()["passwordHash"]);
  if (!isMatchPassword)
    throw exceptions::ValidationException("Mật khẩu hiện tại không đúng!");

  return updateUserPassword(userId, newPassword);
}

bool AuthService::updateUserPassword(int userId,
                                     const std::string& newPassword) {
  json users = utils::storage::readJsonFile("data/users.json");

  for (auto& user : users) {
    if (user["id"] == userId) {
      user["passwordHash"] = utils::hash::generatePasswordHash(newPassword);
      user["isPasswordAutoGenerated"] = false;

      utils::storage::writeJsonFile("data/users.json", users);

      return true;
    }
  }

  throw exceptions::NotFoundException("User không tồn tại");
}

}  // namespace services