#include "seeds/MySeed.hpp"

json adminAccount = {{"username", "admin"},
                     {"password", "123456"},
                     {"email", "admin@gmail.com"},
                     {"fullName", "admin name"},
                     {"isAdmin", true},
                     {"isPasswordAutoGenerated", false}};

json adminWallet = {{
                        "point",
                        100.00,
                    },
                    {"walletType", models::WalletType::SYSTEM}};

namespace seeds {

bool Seed::initialize() {
  if (isSeeded()) return true;

  seedFiles();
  seedData();

  utils::MessageHandler::logSuccess("Khởi tạo dữ liệu thành công!\n");

  return true;
}

bool Seed::seedFiles() {
  std::vector<std::string> requiredFiles = {"data/otps.json", "data/users.json",
                                            "data/wallets.json"};

  utils::MessageHandler::logMessage("\n📁 Đang tạo các file cần thiết:");
  utils::MessageHandler::logMessage("└─────────────────────────────");

  for (const std::string& path : requiredFiles) {
    utils::storage::createFile(path);
    utils::MessageHandler::logMessage("  ├─ " + path + " ✓");
  }
  utils::MessageHandler::logMessage("└─────────────────────────────\n");

  return true;
}

bool Seed::seedData() {
  // Tạo admin
  models::User admin = services::UserService::createUser(
      adminAccount["username"], adminAccount["password"], adminAccount["email"],
      adminAccount["fullName"], adminAccount["isAdmin"],
      adminAccount["isPasswordAutoGenerated"]);
  services::UserService::saveUser(admin);

  // Tạo ví cho admin
  services::WalletService::createWallet(admin.getId(), adminWallet["point"],
                                        adminWallet["walletType"]);

  utils::MessageHandler::logMessage("\n👤 Đang tạo tài khoản admin:");
  utils::MessageHandler::logMessage("└─────────────────────────────");
  utils::MessageHandler::logMessage("  ├─ Tên đăng nhập: " +
                                    std::string(adminAccount["username"]));
  utils::MessageHandler::logMessage("  ├─ Mật khẩu: " +
                                    std::string(adminAccount["password"]));
  utils::MessageHandler::logMessage("  ├─ Email: " +
                                    std::string(adminAccount["email"]));
  utils::MessageHandler::logMessage("  ├─ Họ và tên: " +
                                    std::string(adminAccount["fullName"]));
  utils::MessageHandler::logMessage(
      "  └─ Số điểm: " +
      utils::format::formatPoint(adminWallet["point"].get<double>()) + " điểm");
  utils::MessageHandler::logMessage("└─────────────────────────────\n");
  return true;
}

bool Seed::isSeeded() { return utils::storage::fileExists("data/users.json"); }

}  // namespace seeds