#pragma once

#include <ctime>
#include <nlohmann/json.hpp>
#include <string>

using json = nlohmann::json;

namespace models {

class User {
 private:
  int id;
  std::string username;          // Tên đăng nhập (unique)
  std::string passwordHash;      // Mật khẩu đã được hash
  std::string email;             // Email
  std::string fullName;          // Họ và tên đầy đủ
  bool isAdmin;                  // Phân quyền admin
  bool isPasswordAutoGenerated;  // Bool check mật khẩu tự động tạo

 public:
  
  /**
   * @brief Constructor khởi tạo đối tượng User.
   * @param id ID duy nhất của người dùng.
   * @param username Tên đăng nhập (unique).
   * @param passwordHash Mật khẩu đã được hash.
   * @param email Địa chỉ email.
   * @param fullName Họ và tên đầy đủ.
   * @param isAdmin (Optional) Có phải admin hay không. Mặc định = false.
   * @param isPasswordAutoGenerated (Optional) Mật khẩu có được tự động tạo hay không. Mặc định = false.
   */
  User(int id, const std::string& username, const std::string& passwordHash,
       const std::string& email, const std::string& fullName,
       bool isAdmin = false, bool isPasswordAutoGenerated = false);

  /**
   * @brief Lấy ID của người dùng.
   * @return ID (int).
   */
  int getId() const;

  /**
   * @brief Lấy tên đăng nhập của người dùng.
   * @return Tên đăng nhập (string).
   */
  std::string getUsername() const;

  /**
   * @brief Lấy họ và tên đầy đủ.
   * @return Họ và tên (string).
   */
  std::string getFullName() const;

  /**
   * @brief Lấy email của người dùng.
   * @return Email (string).
   */
  std::string getEmail() const;

  /**
   * @brief Kiểm tra người dùng có quyền admin hay không.
   * @return true nếu là admin, false nếu không.
   */
  bool isAdminUser() const;

  /**
   * @brief Lấy mật khẩu đã hash.
   * @return Mật khẩu hash (string).
   */
  std::string getPasswordHash() const;

  /**
   * @brief Kiểm tra mật khẩu có được tạo tự động hay không.
   * @return true nếu tự động tạo, false nếu không.
   */
  bool getIsPasswordAutoGenerated() const;

  /**
   * @brief Cập nhật trạng thái mật khẩu tự động tạo.
   * @param value true nếu mật khẩu tự động tạo, false nếu không.
   */
  void setIsPasswordAutoGenerated(bool value);

  /**
   * @brief Chuyển đối tượng User sang JSON.
   * @return Đối tượng JSON chứa thông tin người dùng.
   */
  json toJson() const;

  /**
   * @brief Tạo đối tượng User từ dữ liệu JSON.
   * @param jsonData Dữ liệu JSON chứa thông tin người dùng.
   * @return Đối tượng User được khởi tạo từ JSON.
   */
  static User fromJson(const json& jsonData);
};

}  // namespace models
