#ifndef USER_HPP
#define USER_HPP

#include <ctime>
#include <string>

namespace models {

class User {
 private:
  int id;
  std::string username;          // Tên đăng nhập (unique)
  std::string passwordHash;      // Mật khẩu đã được hash
  std::string email;             // Email
  std::string fullName;          // Họ và tên đầy đủ
  bool isAdmin;                  // Phân quyền admin
  bool isPasswordAutoGenerated;  // Bool check mật khẩu tự động tạo
  std::string otpSecret;         // OTP secret
  time_t createdAt;              // Thời gian tạo

 public:
  // Constructor
  User(const std::string& username, const std::string& passwordHash,
       const std::string& email, const std::string& fullName,
       bool isAdmin = false, bool isPasswordAutoGenerated = false,
       const std::string& otpSecret = "", int id = -1);

  // Getters
  int getId() const;
  std::string getUsername() const;
  std::string getFullName() const;
  std::string getEmail() const;
  bool isAdminUser() const;
  std::string getPasswordHash() const;
  bool getIsPasswordAutoGenerated() const;
  std::string getOtpSecret() const;
  time_t getCreatedAt() const;

  // Setters
  void setPassword(const std::string& newPassword);
  void setFullName(const std::string& newFullName);
  void setIsPasswordAutoGenerated(bool value);
  void setOtpSecret(const std::string& secret);
};

}  // namespace models

#endif