#include "models/User.hpp"

#include <string>

#include "utils/Hash.hpp"

namespace models {

// Constructor
User::User(const std::string& username, const std::string& passwordHash,
           const std::string& email, const std::string& fullName, bool isAdmin,
           bool isPasswordAutoGenerated, int id)
    : id(id),
      username(username),
      passwordHash(passwordHash),
      email(email),
      fullName(fullName),
      isAdmin(isAdmin),
      isPasswordAutoGenerated(isPasswordAutoGenerated) {
  createdAt = time(nullptr);  // Set current time
}

// Getters
int User::getId() const { return id; }
std::string User::getUsername() const { return username; }
std::string User::getFullName() const { return fullName; }
std::string User::getEmail() const { return email; }
bool User::isAdminUser() const { return isAdmin; }
std::string User::getPasswordHash() const { return passwordHash; }
bool User::getIsPasswordAutoGenerated() const {
  return isPasswordAutoGenerated;
}
time_t User::getCreatedAt() const { return createdAt; }

// Setters
void User::setPassword(const std::string& newPassword) {
  passwordHash = utils::hash::generatePasswordHash(newPassword);
}

void User::setFullName(const std::string& newFullName) {
  fullName = newFullName;
}

void User::setIsPasswordAutoGenerated(bool value) {
  isPasswordAutoGenerated = value;
}

}  // namespace models